# Generated by Django 4.1.7 on 2023-03-29 07:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=15, null=True)),
                ('size', models.IntegerField(default=0)),
                ('duration_secs', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'media',
                'ordering': ['name', 'type'],
            },
            managers=[
                ('image', django.db.models.manager.Manager()),
            ],
        ),
    ]
