# Generated by Django 4.1.7 on 2023-04-02 16:33

import custom_validator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Int_Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even', models.IntegerField(validators=[custom_validator.models.even_validator])),
                ('email', models.EmailField(max_length=254, validators=[custom_validator.models.gmail_validator])),
            ],
            options={
                'db_table': 'int_char',
                'ordering': ['even', 'email'],
            },
        ),
    ]
