# Generated by Django 4.1.7 on 2023-03-30 10:58

import django.core.validators
from django.db import migrations, models
import validapp.validatore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=15, null=True)),
                ('salary', models.IntegerField(verbose_name=5000000)),
                ('notice_period', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)])),
                ('age', models.IntegerField(default=2000, validators=[validapp.validatore.Validate_age])),
            ],
            options={
                'db_table': 'jobsearch',
                'ordering': ['name', 'role'],
            },
        ),
    ]
